spring.application.name=Practise_spring
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true

gemini.api.key=${GEMINI_API_KEY}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
